
spring.application.name=tiendaPandora
server.port=8081

# =========================
# Spring Config
# =========================
spring.config.import=optional:file:.env[.properties]

# =========================
# DATABASE
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# LOGGING
# =========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# SECRET_KEY
# ===============================
jwt.secret=${SECRET_KEY}

# ===============================
# OAuth
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_ID_CLIENTE}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENTE_SECRET}